'use strict';
'require view';
'require form';
'require uci';
'require rpc';
'require ui';

var callImport = rpc.declare({
	object: 'luci.trusttunnel', method: 'import_config', params: [ 'text' ]
});

// Все настройки собраны на ОДНОЙ странице с вкладками, а не разложены по
// отдельным пунктам меню. Причина не в экономии: в LuCI каждый пункт меню —
// это отдельная страница, и переход между ними перезагружает всю оболочку
// целиком. Настройка пакета — это один сеанс работы (задать сервер, добавить
// исключения), и разрывать его тремя перезагрузками неправильно. Штатные
// страницы LuCI устроены так же: «Система» держит пять вкладок в одной
// странице, «DHCP и DNS» и «Интерфейсы» — тоже.
//
// Механизм: m.tabbed = true превращает каждую секцию в вкладку, а её заголовок
// становится названием вкладки. Переключение происходит в браузере, без запроса
// к роутеру.
return view.extend({
	load: function() {
		return uci.load('trusttunnel');
	},

	handleImport: function() {
		var ta = E('textarea', {
			'rows': 14, 'style': 'width:100%',
			'placeholder': _('Paste the endpoint configuration generated by your server')
		});
		ui.showModal(_('Import endpoint configuration'), [
			E('p', {}, _('Accepts both forms a server hands out: the configuration file text and a tt:// link. Nothing is saved until you press Save & Apply.')),
			ta,
			E('div', { 'class': 'right' }, [
				E('button', { 'class': 'btn', 'click': ui.hideModal }, _('Cancel')),
				' ',
				E('button', {
					'class': 'cbi-button cbi-button-positive',
					'click': ui.createHandlerFn(this, function() {
						return callImport(ta.value).then(function(res) {
							if (res.error) {
								ui.addNotification(null, E('p', {}, res.error), 'danger');
								return;
							}
							if (res.hostname)
								uci.set('trusttunnel', 'endpoint', 'hostname', res.hostname);
							if (res.username)
								uci.set('trusttunnel', 'endpoint', 'username', res.username);
							if (res.password)
								uci.set('trusttunnel', 'endpoint', 'password', res.password);
							if (res.certificate)
								uci.set('trusttunnel', 'endpoint', 'certificate', res.certificate);
							if (res.addresses && res.addresses.length)
								uci.set('trusttunnel', 'endpoint', 'address', res.addresses);

							// uci.set() держит изменения только в памяти
							// браузера. Перезагрузка страницы их выбрасывает,
							// поэтому прежний вариант (set + location.reload)
							// показывал «импортировано», а через 800 мс молча
							// возвращал прежние значения — импорт выглядел
							// работающим и не работал.
							//
							// uci.save() отправляет изменения на роутер как
							// ОТЛОЖЕННЫЕ: конфиг не применяется, службы не
							// перезапускаются, LuCI показывает «есть
							// несохранённые изменения». После перезагрузки
							// страницы поля показывают импортированное, а
							// применяет их пользователь сам — то есть условие
							// «импорт ничего не применяет» соблюдено.
							return uci.save().then(function() {
								ui.hideModal();
								ui.addNotification(null, E('p', {},
									_('Imported. Review the fields and press Save & Apply.')), 'info');
								window.setTimeout(function() { location.reload(); }, 800);
							});
						}).catch(function(e) {
							ui.addNotification(null, E('p', {}, e.message || String(e)), 'danger');
						});
					})
				}, _('Import'))
			])
		]);
	},

	render: function(data) {
		var m, s, o;

		m = new form.Map('trusttunnel', _('TrustTunnel'));
		// Каждая секция становится вкладкой. Прецедент в штатных страницах:
		// network/dhcp, network/interfaces, network/routes, system/flash.
		m.tabbed = true;

		// --- Общее -----------------------------------------------------------
		s = m.section(form.NamedSection, 'main', 'main', _('General'));

		o = s.option(form.Flag, 'enabled', _('Start on boot'),
			_('Whether the service starts when the router boots. The Start button on the Status page runs it right now.'));
		o.rmempty = false;

		o = s.option(form.ListValue, 'log_level', _('Log level'));
		o.value('info', 'info');
		o.value('debug', 'debug');
		o.value('trace', 'trace');
		o.description = _('debug and trace write a lot; leave them on only while investigating something.');

		// --- Сервер ----------------------------------------------------------
		s = m.section(form.NamedSection, 'endpoint', 'endpoint', _('Server'));

		o = s.option(form.Button, '_import', _('Server configuration'),
			_('The fast path: paste what your server generated and the fields below fill themselves in.'));
		o.inputtitle = _('Import…');
		o.inputstyle = 'action';
		o.onclick = ui.createHandlerFn(this, 'handleImport');

		o = s.option(form.DynamicList, 'address', _('Addresses'),
			_('host:port or [ipv6]:port. With several addresses the client measures them and picks the fastest.'));
		o.placeholder = '203.0.113.10:443';
		o.rmempty = false;

		o = s.option(form.Value, 'hostname', _('TLS host name'),
			_('Used for the TLS session, not for routing. Without it many servers refuse the connection.'));
		o.datatype = 'hostname';
		o.rmempty = false;

		o = s.option(form.Value, 'username', _('User name'));
		o.rmempty = false;

		o = s.option(form.Value, 'password', _('Password'));
		o.password = true;
		o.rmempty = false;

		o = s.option(form.ListValue, 'protocol', _('Transport'));
		o.value('http2', 'HTTP/2');
		o.value('http3', 'HTTP/3 (QUIC)');
		o.description = _('QUIC is often faster, but some networks throttle or block UDP.');

		o = s.option(form.Flag, 'anti_dpi', _('Anti-DPI'),
			_('Countermeasures against traffic inspection. Worth enabling if the connection establishes but keeps dropping.'));

		o = s.option(form.Flag, 'post_quantum', _('Post-quantum key exchange'));
		o.default = '1';

		o = s.option(form.Flag, 'has_ipv6', _('Server carries IPv6'));
		o.default = '1';

		o = s.option(form.Flag, 'skip_verification', _('Skip certificate verification'),
			_('Accepts any certificate, which removes the protection against a substituted server. Pin the certificate below instead whenever you can.'));

		o = s.option(form.TextValue, 'certificate', _('Pinned certificate (PEM)'),
			_('Leave empty to use the system trust store, which requires the ca-bundle package.'));
		o.rows = 6;
		o.optional = true;

		o = s.option(form.DynamicList, 'dns_upstream', _('DNS used by the client itself'),
			_('Applies to what the TrustTunnel client resolves on its own — for example the exclusion domains it pre-resolves. Empty means the client default, AdGuard DNS unfiltered.'));
		o.placeholder = 'tls://1.1.1.1';
		// Форматы взяты из эталонного конфига, который генерирует сам
		// setup_wizard: обычный DNS, tcp://, tls://, https://, quic:// и
		// sdns://. Предустановки — готовые строки этих форматов; своё значение
		// вписывается тут же, список их не ограничивает.
		o.value('tls://1.1.1.1', 'Cloudflare — DNS over TLS');
		o.value('tls://9.9.9.9', 'Quad9 — DNS over TLS');
		o.value('tls://dns.adguard-dns.com', 'AdGuard — DNS over TLS');
		o.value('https://cloudflare-dns.com/dns-query', 'Cloudflare — DNS over HTTPS');
		o.value('https://dns.quad9.net/dns-query', 'Quad9 — DNS over HTTPS');
		o.value('quic://dns.adguard-dns.com', 'AdGuard — DNS over QUIC');
		o.value('1.1.1.1:53', 'Cloudflare — ' + _('plain DNS'));
		o.value('9.9.9.9:53', 'Quad9 — ' + _('plain DNS'));

		// --- Исключения ------------------------------------------------------
		s = m.section(form.NamedSection, 'domains', 'domains', _('Exclusions'));
		s.description = _('Everything goes through the tunnel; these entries always go out directly. The client applies them by SNI, after the kernel has already marked the traffic.');

		o = s.option(form.DynamicList, 'direct', _('Do not bypass these'),
			_('Always sent out directly. Accepts a domain, *.domain, an IP address or a CIDR range.'));
		o.placeholder = 'bank.example';
		o.validate = function(section_id, value) {
			if (!value) return true;
			var v = value.toLowerCase();
			if (/^\*\./.test(v)) v = v.slice(2);
			if (/^[0-9a-f:.\/]+$/.test(v)) return true;
			if (!/^[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)*$/.test(v))
				return _('Not a valid domain, IP address or CIDR range');
			return true;
		};

		// --- Сеть ------------------------------------------------------------
		s = m.section(form.NamedSection, 'network', 'network', _('Network'));
		s.description = _('These rarely need changing. MTU is the exception: too high a value makes small pages load while TLS handshakes and large downloads stall.');

		// Поля «устройство TUN» здесь БОЛЬШЕ НЕТ. Имя устройства выбирает сам
		// клиент, а не мы: ключей для его задания в схеме клиента не существует.
		// Оставлять поле означало бы предлагать настройку, которая ни на что не
		// влияет. Фактическое имя показано на странице состояния.
		o = s.option(form.Value, 'mtu', _('MTU'));
		o.datatype = 'range(576,9000)';
		o.default = '1350';

		o = s.option(form.Value, 'lan_devices', _('LAN interfaces'),
			_('Space-separated list whose forwarded traffic is considered. Empty means the device of the lan network.'));
		o.placeholder = 'br-lan';
		o.optional = true;

		o = s.option(form.Flag, 'blackhole_on_down', _('Drop traffic when the tunnel is down'),
			_('Adds a blackhole route so marked traffic is dropped instead of leaking to the provider.'));
		o.default = '1';

		o = s.option(form.Flag, 'include_router_traffic', _('Route the router\'s own traffic too'),
			_('By default only forwarded LAN traffic is routed. Enabling this also routes traffic originated by the router itself, including the update check.'));

		// Метка идёт прямо в `ip rule add fwmark …`, поэтому формат проверяем
		// здесь: без проверки мусорное значение доходит до ядра, `ip rule`
		// падает, а его stderr никуда не всплывает — маршрутизация остаётся
		// собранной наполовину и молча.
		o = s.option(form.Value, 'fwmark', _('Firewall mark'),
			_('Decimal or 0x-prefixed hexadecimal. Change only on a conflict with mwan3, SQM or another package that marks packets.'));
		o.default = '0x9527';
		o.validate = function(section_id, value) {
			if (!value) return true;
			if (!/^(0x[0-9a-fA-F]{1,8}|[0-9]{1,10})$/.test(value))
				return _('Enter a decimal number or 0x-prefixed hexadecimal');
			// Ограничение на число цифр (до 10) само по себе не отсекает
			// значение, превышающее 32-битный максимум: "9999999999" проходит
			// эту проверку по форме, хотя fwmark — 32-битное поле в ядре.
			if (!/^0x/i.test(value) && +value > 4294967295)
				return _('Enter a decimal number no greater than 4294967295');
			return true;
		};

		// НЕ range(1,252). Идентификатор таблицы маршрутизации в Linux
		// 32-битный, и значение по умолчанию 880 выбрано именно чтобы не
		// пересекаться с диапазоном, который занимают другие пакеты.
		// Проверено на живом OpenWrt: ядро принимает и 880, и 900.
		// Ограничение 1..252 отвергало бы штатную конфигурацию, то есть
		// страницу настроек нельзя было бы сохранить из коробки.
		// Исключаются только 0 и 253..255 — это main, default и local,
		// перехват которых сломал бы маршрутизацию всей системы.
		o = s.option(form.Value, 'table', _('Routing table'),
			_('Any table id except 0 and the reserved 253-255.'));
		o.datatype = 'uinteger';
		o.default = '880';
		o.validate = function(section_id, value) {
			if (!value) return true;
			var n = +value;
			if (!/^[0-9]+$/.test(value) || n < 1 || n > 4294967294)
				return _('Enter a table id between 1 and 4294967294');
			if (n >= 253 && n <= 255)
				return _('Table ids 253, 254 and 255 are reserved by the system');
			return true;
		};

		return m.render();
	}
});
