'use strict';
'require view';
'require form';
'require uci';
'require rpc';
'require ui';

var callImport = rpc.declare({
	object: 'luci.trusttunnel', method: 'import_config', params: [ 'text' ]
});

// All settings are gathered on ONE page with tabs, not spread across
// separate menu items. The reason is not economy: in LuCI every menu item
// is a separate page, and moving between them reloads the whole shell
// entirely. Configuring the package is one working session (set the server,
// add the exclusions), and breaking it with three reloads is wrong. The
// stock LuCI pages work the same way: "System" keeps five tabs in one page,
// and "DHCP and DNS" and "Interfaces" do too.
//
// The mechanism: m.tabbed = true turns every section into a tab, and its
// title becomes the tab name. Switching happens in the browser, without a
// request to the router.
return view.extend({
	load: function() {
		return uci.load('trusttunnel');
	},

	handleImport: function() {
		var ta = E('textarea', {
			'rows': 14, 'style': 'width:100%',
			'placeholder': _('Paste the endpoint configuration generated by your server')
		});
		ui.showModal(_('Import endpoint configuration'), [
			E('p', {}, _('Accepts both forms a server hands out: the configuration file text and a tt:// link. Nothing is saved until you press Save & Apply.')),
			ta,
			E('div', { 'class': 'right' }, [
				E('button', { 'class': 'btn', 'click': ui.hideModal }, _('Cancel')),
				' ',
				E('button', {
					'class': 'cbi-button cbi-button-positive',
					'click': ui.createHandlerFn(this, function() {
						return callImport(ta.value).then(function(res) {
							if (res.error) {
								ui.addNotification(null, E('p', {}, res.error), 'danger');
								return;
							}
							if (res.hostname)
								uci.set('trusttunnel', 'endpoint', 'hostname', res.hostname);
							if (res.username)
								uci.set('trusttunnel', 'endpoint', 'username', res.username);
							if (res.password)
								uci.set('trusttunnel', 'endpoint', 'password', res.password);
							if (res.certificate)
								uci.set('trusttunnel', 'endpoint', 'certificate', res.certificate);
							if (res.addresses && res.addresses.length)
								uci.set('trusttunnel', 'endpoint', 'address', res.addresses);

							// uci.set() keeps changes only in the browser's
							// memory. A page reload throws them away, so the
							// old variant (set + location.reload) showed
							// "imported" and 800 ms later silently restored
							// the previous values — the import looked like
							// it worked and did not.
							//
							// uci.save() sends the changes to the router as
							// PENDING: the config is not applied, services
							// are not restarted, LuCI shows "there are
							// unsaved changes". After a page reload the
							// fields show the imported values, and the user
							// applies them themselves — the "import applies
							// nothing" condition is satisfied.
							return uci.save().then(function() {
								ui.hideModal();
								ui.addNotification(null, E('p', {},
									_('Imported. Review the fields and press Save & Apply.')), 'info');
								window.setTimeout(function() { location.reload(); }, 800);
							});
						}).catch(function(e) {
							ui.addNotification(null, E('p', {}, e.message || String(e)), 'danger');
						});
					})
				}, _('Import'))
			])
		]);
	},

	render: function(data) {
		var m, s, o;

		m = new form.Map('trusttunnel', _('TrustTunnel'));
		// Every section becomes a tab. Precedent in the stock pages:
		// network/dhcp, network/interfaces, network/routes, system/flash.
		m.tabbed = true;

		// --- General -------------------------------------------------------
		s = m.section(form.NamedSection, 'main', 'main', _('General'));

		o = s.option(form.Flag, 'enabled', _('Start on boot'),
			_('Whether the service starts when the router boots. The Start button on the Status page runs it right now.'));
		o.rmempty = false;

		o = s.option(form.ListValue, 'log_level', _('Log level'));
		o.value('info', 'info');
		o.value('debug', 'debug');
		o.value('trace', 'trace');
		o.description = _('debug and trace write a lot; leave them on only while investigating something.');

		// --- Server -------------------------------------------------------
		s = m.section(form.NamedSection, 'endpoint', 'endpoint', _('Server'));

		o = s.option(form.Button, '_import', _('Server configuration'),
			_('The fast path: paste what your server generated and the fields below fill themselves in.'));
		o.inputtitle = _('Import…');
		o.inputstyle = 'action';
		o.onclick = ui.createHandlerFn(this, 'handleImport');

		o = s.option(form.DynamicList, 'address', _('Addresses'),
			_('host:port or [ipv6]:port. With several addresses the client measures them and picks the fastest.'));
		o.placeholder = '203.0.113.10:443';
		o.rmempty = false;

		o = s.option(form.Value, 'hostname', _('TLS host name'),
			_('Used for the TLS session, not for routing. Without it many servers refuse the connection.'));
		o.datatype = 'hostname';
		o.rmempty = false;

		o = s.option(form.Value, 'username', _('User name'));
		o.rmempty = false;

		o = s.option(form.Value, 'password', _('Password'));
		o.password = true;
		o.rmempty = false;

		o = s.option(form.ListValue, 'protocol', _('Transport'));
		o.value('http2', 'HTTP/2');
		o.value('http3', 'HTTP/3 (QUIC)');
		o.description = _('QUIC is often faster, but some networks throttle or block UDP.');

		o = s.option(form.Flag, 'anti_dpi', _('Anti-DPI'),
			_('Countermeasures against traffic inspection. Worth enabling if the connection establishes but keeps dropping.'));

		o = s.option(form.Flag, 'post_quantum', _('Post-quantum key exchange'));
		o.default = '1';

		o = s.option(form.Flag, 'has_ipv6', _('Server carries IPv6'));
		o.default = '1';

		o = s.option(form.Flag, 'skip_verification', _('Skip certificate verification'),
			_('Accepts any certificate, which removes the protection against a substituted server. Pin the certificate below instead whenever you can.'));

		o = s.option(form.TextValue, 'certificate', _('Pinned certificate (PEM)'),
			_('Leave empty to use the system trust store, which requires the ca-bundle package.'));
		o.rows = 6;
		o.optional = true;

		o = s.option(form.DynamicList, 'dns_upstream', _('DNS used by the client itself'),
			_('Applies to what the TrustTunnel client resolves on its own — for example the exclusion domains it pre-resolves. Empty means the client default, AdGuard DNS unfiltered.'));
		o.placeholder = 'tls://1.1.1.1';
		// The formats are taken from the reference config that setup_wizard
		// itself generates: plain DNS, tcp://, tls://, https://, quic:// and
		// sdns://. The presets are ready-made strings of these formats; a
		// custom value can be typed right there, the list does not restrict it.
		o.value('tls://1.1.1.1', 'Cloudflare — DNS over TLS');
		o.value('tls://9.9.9.9', 'Quad9 — DNS over TLS');
		o.value('tls://dns.adguard-dns.com', 'AdGuard — DNS over TLS');
		o.value('https://cloudflare-dns.com/dns-query', 'Cloudflare — DNS over HTTPS');
		o.value('https://dns.quad9.net/dns-query', 'Quad9 — DNS over HTTPS');
		o.value('quic://dns.adguard-dns.com', 'AdGuard — DNS over QUIC');
		o.value('1.1.1.1:53', 'Cloudflare — ' + _('plain DNS'));
		o.value('9.9.9.9:53', 'Quad9 — ' + _('plain DNS'));

		// --- Exclusions ----------------------------------------------------
		s = m.section(form.NamedSection, 'domains', 'domains', _('Exclusions'));
		s.description = _('Everything goes through the tunnel; these entries always go out directly. The client applies them by SNI, after the kernel has already marked the traffic.');

		o = s.option(form.DynamicList, 'direct', _('Do not bypass these'),
			_('Always sent out directly. Accepts a domain, *.domain, an IP address or a CIDR range.'));
		o.placeholder = 'bank.example';
		o.validate = function(section_id, value) {
			if (!value) return true;
			var v = value.toLowerCase();
			if (/^\*\./.test(v)) v = v.slice(2);
			if (/^[0-9a-f:.\/]+$/.test(v)) return true;
			if (!/^[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)*$/.test(v))
				return _('Not a valid domain, IP address or CIDR range');
			return true;
		};

		// --- Network -------------------------------------------------------
		s = m.section(form.NamedSection, 'network', 'network', _('Network'));
		s.description = _('These rarely need changing. MTU is the exception: too high a value makes small pages load while TLS handshakes and large downloads stall.');

		// The "TUN device" field is GONE here. The device name is chosen by
		// the client itself, not by us: there are no keys for setting it in
		// the client schema. Keeping the field would mean offering a setting
		// that affects nothing. The actual name is shown on the status page.
		o = s.option(form.Value, 'mtu', _('MTU'));
		o.datatype = 'range(576,9000)';
		o.default = '1350';

		o = s.option(form.Value, 'lan_devices', _('LAN interfaces'),
			_('Space-separated list whose forwarded traffic is considered. Empty means the device of the lan network.'));
		o.placeholder = 'br-lan';
		o.optional = true;

		o = s.option(form.Flag, 'blackhole_on_down', _('Drop traffic when the tunnel is down'),
			_('Adds a blackhole route so marked traffic is dropped instead of leaking to the provider.'));
		o.default = '1';

		o = s.option(form.Flag, 'include_router_traffic', _('Route the router\'s own traffic too'),
			_('By default only forwarded LAN traffic is routed. Enabling this also routes traffic originated by the router itself, including the update check.'));

		// The mark goes straight into `ip rule add fwmark …`, so the format
		// is validated here: without validation a garbage value reaches the
		// kernel, `ip rule` fails, and its stderr never surfaces — routing
		// stays half-assembled, silently.
		o = s.option(form.Value, 'fwmark', _('Firewall mark'),
			_('Decimal or 0x-prefixed hexadecimal. Change only on a conflict with mwan3, SQM or another package that marks packets.'));
		o.default = '0x9527';
		o.validate = function(section_id, value) {
			if (!value) return true;
			if (!/^(0x[0-9a-fA-F]{1,8}|[0-9]{1,10})$/.test(value))
				return _('Enter a decimal number or 0x-prefixed hexadecimal');
			// The digit-count limit (up to 10) alone does not reject a value
			// exceeding the 32-bit maximum: "9999999999" passes that check
			// by form, although fwmark is a 32-bit field in the kernel.
			if (!/^0x/i.test(value) && +value > 4294967295)
				return _('Enter a decimal number no greater than 4294967295');
			return true;
		};

		// NOT range(1,252). The routing table id in Linux is 32-bit, and the
		// default value 880 was chosen precisely to avoid overlapping the
		// range occupied by other packages. Verified on a live OpenWrt: the
		// kernel accepts both 880 and 900. The 1..252 limit would reject the
		// stock configuration, i.e. the settings page could not be saved out
		// of the box. Only 0 and 253..255 are excluded — these are main,
		// default and local, hijacking them would break routing of the whole
		// system.
		o = s.option(form.Value, 'table', _('Routing table'),
			_('Any table id except 0 and the reserved 253-255.'));
		o.datatype = 'uinteger';
		o.default = '880';
		o.validate = function(section_id, value) {
			if (!value) return true;
			var n = +value;
			if (!/^[0-9]+$/.test(value) || n < 1 || n > 4294967294)
				return _('Enter a table id between 1 and 4294967294');
			if (n >= 253 && n <= 255)
				return _('Table ids 253, 254 and 255 are reserved by the system');
			return true;
		};

		return m.render();
	}
});
